# Generated by Django 4.2.9 on 2024-02-08 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nutritional_table.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(blank=True, default=dict, null=True, verbose_name='recommendations')),
                ('ocr_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='ocr data')),
                ('file_table', models.FileField(blank=True, null=True, upload_to=nutritional_table.utils.upload_user_file, validators=[nutritional_table.utils.validate_file], verbose_name='file table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nutritionaltable_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Nutritional table',
                'verbose_name_plural': 'Nutritional tables',
            },
        ),
    ]
