# Generated by Django 4.2.9 on 2024-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaltable',
            name='name',
            field=models.CharField(default='prueba', max_length=100, unique=True, verbose_name='nutrient name'),
            preserve_default=False,
        ),
    ]
