# Generated by Django 4.2.9 on 2024-03-30 00:51

from django.db import migrations, models
import nutritional_table.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_table', '0002_nutritionaltable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaltable',
            name='file_table_processed',
            field=models.FileField(blank=True, null=True, upload_to=nutritional_table.utils.upload_user_file_processed, validators=[nutritional_table.utils.validate_file], verbose_name='file table processed'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='recommendations',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='user response'),
        ),
    ]
