# Generated by Django 4.2.9 on 2024-03-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_table', '0003_nutritionaltable_file_table_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaltable',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pendiente'), (1, 'Actualizado')], default=0, null=True, verbose_name='estado'),
        ),
    ]
