# Generated by Django 4.2.9 on 2024-04-03 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nutritional_table.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutritional_table', '0004_nutritionaltable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionaltable',
            name='file_table',
            field=models.FileField(blank=True, null=True, upload_to=nutritional_table.utils.upload_user_file, validators=[nutritional_table.utils.validate_file], verbose_name='archivo de tabla original'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='file_table_processed',
            field=models.FileField(blank=True, null=True, upload_to=nutritional_table.utils.upload_user_file_processed, validators=[nutritional_table.utils.validate_file], verbose_name='archivo de tabla procesada'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='ocr_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='datos ocr'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='recommendations',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='respuesta usuario'),
        ),
        migrations.AlterField(
            model_name='nutritionaltable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nutritionaltable_set', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
