# Generated by Django 4.2.9 on 2024-04-13 16:24

from django.db import migrations, models
import nutritional_table.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_table', '0005_alter_nutritionaltable_file_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionaltable',
            name='file_table',
            field=models.FileField(null=True, upload_to=nutritional_table.utils.upload_user_file, validators=[nutritional_table.utils.validate_file], verbose_name='archivo de tabla original'),
        ),
    ]
