# Generated by Django 4.2.9 on 2024-02-07 04:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrient', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True, verbose_name='information')),
                ('life_stage', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Infant'), (1, 'Child'), (2, 'Female'), (3, 'Male'), (4, 'Pregnancy'), (5, 'Breastfeeding')], default=0, null=True, verbose_name='life stage')),
                ('max_age_range', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum age range')),
                ('min_age_range', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimun age range')),
                ('recommendable_quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='recommendable quantity')),
                ('bibliography', models.TextField(blank=True, null=True, verbose_name='bibliography')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_dailyquantity_set', to='nutrient.nutrient', verbose_name='nutrient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_dailyquantity_set', to='unit.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Daily quantity',
                'verbose_name_plural': 'Daily quantities',
            },
        ),
    ]
