# Generated by Django 4.2.9 on 2024-02-06 02:45

import customized.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nutrient name')),
            ],
            options={
                'verbose_name': 'Nutrient',
                'verbose_name_plural': 'Nutrients',
            },
            bases=(customized.mixin.SlugModelMixin, models.Model),
        ),
    ]
