# Generated by Django 4.2.9 on 2024-03-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='cached_recommendations',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='recommendations'),
        ),
    ]
