# Generated by Django 4.2.9 on 2024-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='physiological_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pregnancy'), (1, 'Breastfeeding'), (2, 'Not Apply')], default=2, null=True, verbose_name='physiological state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], default=0, null=True, verbose_name='gender'),
        ),
    ]
