# Generated by Django 4.2.9 on 2024-03-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_physiological_state_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='physical_activity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Menos de 30 minutos de actividad moderada al día'), (1, 'Entre 30 y 60 minutos de actividad moderada al día'), (2, 'Más de 60 minutos de actividad moderada al día')], default=0, null=True, verbose_name='physical activity'),
        ),
    ]
