# Generated by Django 4.2.9 on 2024-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_physical_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='physical_activity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sedentario (poco o nada de ejercicio + trabajo de escritorio)'), (1, 'Ligeramente activo (ejercicio ligero 1-3 días / semana)'), (2, 'Moderadamente activo (ejercicio moderado 3-5 días / semana)'), (3, 'Muy activo (ejercicio pesado 6-7 días / semana)'), (4, 'Extremadamente activo (entrenamiento extenuante 2x / día)')], default=0, null=True, verbose_name='physical activity'),
        ),
    ]
