# Generated by Django 4.2.9 on 2024-04-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_objective_alter_user_age_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='physical_activity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sedentario'), (1, 'Ligeramente activo'), (2, 'Moderadamente activo'), (3, 'Muy activo'), (4, 'Extremadamente activo')], default=0, null=True, verbose_name='nivel de actividad física'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Femenino'), (1, 'Masculino')], default=0, null=True, verbose_name='genero'),
        ),
    ]
