# Generated by Django 4.2.9 on 2024-02-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True, verbose_name='information')),
                ('type_information', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Definition'), (1, 'Illness')], default=0, null=True, verbose_name='type information')),
                ('cause_illness', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Excess'), (1, 'Failure')], default=0, null=True, verbose_name='cause illness')),
                ('bibliography', models.TextField(blank=True, null=True, verbose_name='bibliography')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_information_set', to='nutrient.nutrient', verbose_name='nutrient')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
    ]
